-- core/domain/enrichment/dispatcher.lua
--
-- Deprecated compatibility shim.
-- Orchestration now flows through:
--   planner -> executor -> mutate
--
-- This module is intentionally inert.

-- local Dispatcher = {}
--
-- function Dispatcher.execute()
--     return nil
-- end
--
-- return Dispatcher
