-- core/schema/fields/order.lua
--
-- Order Meta Definition Space
--
-- Authoritative semantic definition for canonical order objects.
-- Pure structural + semantic governance.
-- No ingestion logic.
-- No workflow routing.
-- No persistence logic.

local Order = {}

---@type table<string, FieldRecord>
Order.FIELD = {

    ------------------------------------------------------------
    -- Identity
    ------------------------------------------------------------

    ORDER_ID = {
        kind        = "field",
        domain      = "order",
        name        = "order_id",
        type        = "symbol",
        required    = true,
        default     = nil,
        authority   = "system",       -- generated by runtime
        mutable     = false,          -- immutable once assigned

        groups      = { "identity" },
        description = "System-level unique identifier for stored order record.",
    },

    ORDER_NUMBER = {
        kind        = "field",
        domain      = "order",
        name        = "order_number",
        type        = "string",
        required    = false,
        default     = nil,
        authority   = "authoritative",
        mutable     = true,
        groups      = { "identity", "external" },
        description = "Primary external-facing order identifier.",
    },

    CLIENT_ID = {
        kind        = "field",
        domain      = "order",
        name        = "client_id",
        type        = "symbol",
        required    = false,
        default     = nil,
        authority   = "authoritative",
        mutable     = true,
        groups      = { "identity", "relationship" },
        aliases     = { "customer_id" },
        description = "Canonical client identifier (may be unknown/unset).",
    },

    DATE = {
        kind        = "field",
        domain      = "order",
        name        = "date",
        type        = "string",
        required    = false,
        default     = nil,
        authority   = "authoritative",
        mutable     = true,
        groups      = { "lifecycle", "temporal" },
        description = "Transaction or effective date of the order.",
    },

    ------------------------------------------------------------
    -- Lifecycle
    ------------------------------------------------------------

    STATUS = {
        kind        = "field",
        domain      = "order",
        name        = "order_status",
        type        = "symbol",
        required    = false,
        default     = "open",
        authority   = "system",       -- system-managed lifecycle
        mutable     = true,           -- but allowed to transition

        reference   = "order.status",
        groups      = { "lifecycle" },
        aliases     = { "status" },
        description = "Lifecycle state of the order.",
    },

    USE = {
        kind        = "field",
        domain      = "order",
        name        = "use",
        type        = "symbol",
        required    = false,
        default     = "sale",
        authority   = "authoritative",
        mutable     = true,
        reference   = "order.use",
        groups      = { "classification" },
        description = "Declared intent of the order.",
    },

    ------------------------------------------------------------
    -- Monetary
    ------------------------------------------------------------

    VALUE = {
        kind        = "field",
        domain      = "order",
        name        = "value",
        type        = "number",
        required    = false,
        default     = nil,
        authority   = "derived",      -- usually computed from boards
        mutable     = false,
        unit        = "usd",
        precision   = 2,
        groups      = { "financial", "metrics" },
        description = "Final associated total monetary value of the order.",
    },

    ------------------------------------------------------------
    -- Composition
    ------------------------------------------------------------

    ITEMS = {
        kind        = "field",
        domain      = "order",
        name        = "items",
        type        = "table",
        required    = false,
        default     = nil,
        authority   = "system",
        mutable     = true,
        groups      = { "composition" },
        aliases     = { "boards" },
        description = "List of board objects belonging to this order.",
    },

    ------------------------------------------------------------
    -- Notes
    ------------------------------------------------------------

    NOTES = {
        kind        = "field",
        domain      = "order",
        name        = "order_notes",
        type        = "string",
        required    = false,
        default     = nil,
        authority   = "authoritative",
        mutable     = true,
        groups      = { "annotation" },
        aliases     = { "notes" },
        description = "Free-form notes associated with the order.",
    },

}

return Order
