-- local Schema = require("core.board.schema")
--
-- local MapFields = {}
--
-- ---@param record table
-- ---@return MappedRecord
-- function MapFields.run(record)
--     local out = {
--         ok      = true,
--         data    = {},
--         unknown = {},
--         errors  = {},
--         source  = record,
--     }
--
--     for key, value in pairs(record) do
--         if type(key) ~= "string" or key:match("^_") then
--             goto continue
--         end
--
--         local canonical = Schema.alias_index[key]
--
--         if canonical then
--             out.data[canonical] = value
--         else
--             out.unknown[key] = value
--         end
--
--         ::continue::
--     end
--
--     -- Required declared fields (NOT board invariants yet)
--     if not out.data.base_h and not out.data.h then
--         out.ok = false
--         out.errors[#out.errors + 1] = "missing base_h / h"
--     end
--
--     if not out.data.base_w and not out.data.w then
--         out.ok = false
--         out.errors[#out.errors + 1] = "missing base_w / w"
--     end
--
--     if out.data.l == nil then
--         out.ok = false
--         out.errors[#out.errors + 1] = "missing l"
--     end
--
--     return out
-- end
--
-- return MapFields
